### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by oscarbg** [asbschmidt/CUDASW4#2]
Hi,
just asking if software can be ported/enabled for Windows..
tried building but seems some specific Unix headers/calls like for mmap (https://github.com/asbschmidt/CUDASW4/blob/main/src/mapped_file.hpp) prevent easy compilation..
thanks..

**Comment by fkallen** [comment]
CUDASW4 was developed for Linux. We currently do not have plans to add Windows support. You could try WSL.
